---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-kfk-ephemeral-storage-class
  namespace: confluent
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ephemeral-kfk-1
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-kfk-ephemeral-storage-class
  hostPath:
     path: /mnt/data/cflt/emp/kfk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ephemeral-kfk-2
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-kfk-ephemeral-storage-class
  hostPath:
     path: /mnt/data/cflt/emp/kfk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ephemeral-kfk-3
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-kfk-ephemeral-storage-class
  hostPath:
     path: /mnt/data/cflt/emp/kfk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-03
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-ephemeral-kfk-4
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: local-kfk-ephemeral-storage-class
  hostPath:
     path: /mnt/data/cflt/emp/kfk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-04