---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-zk-retained-storage-class
  namespace: confluent
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-zk-1a
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-zk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/zk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-zk-1b
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-zk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/zk-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-zk-2a
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-zk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/zk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-zk-2b
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-zk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/zk-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-02

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-zk-3a
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-zk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/zk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-03
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-zk-3b
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-zk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/zk-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-03
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-zk-4a
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-zk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/zk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-04
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-zk-4b
  namespace: confluent
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-zk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/zk-2
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-04