---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-kfk-retained-storage-class
  namespace: confluent
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-kfk-1
  namespace: confluent
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-kfk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/kfk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-kfk-2
  namespace: confluent
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-kfk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/kfk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-kfk-3
  namespace: confluent
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-kfk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/kfk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-03
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-retained-kfk-4
  namespace: confluent
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-kfk-retained-storage-class
  local:
     path: /mnt/data/cflt/retain/kfk-1
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k8-rock-node-04